import connectDB from "../config/db.js";
import Gallery from "../models/Gallery.model.js";
import GalleryItem from "../models/GalleryItem.model.js";

const seed = async () => {
  await connectDB();

  const existing = await Gallery.findOne();
  if (existing) {
    console.log("Gallery already seeded");
    process.exit(0);
  }

  // ── COLLECTION 1: Nature & Landscapes ──
  const natureItems = await GalleryItem.insertMany([
    {
      title: "Alpine Sunrise",
      description: "Golden light breaking over snow-capped peaks in the Swiss Alps.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop",
      category: "Mountains",
      tags: ["landscape", "sunrise", "alps"],
      altText: "Alpine sunrise over snow-capped peaks",
      hoverText: "View Alpine Sunrise",
      lightboxEnabled: true,
      order: 1,
      stats: { views: 3420, likes: 287 },
    },
    {
      title: "Ocean Breeze",
      description: "Turquoise waves rolling onto a pristine white-sand beach.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=400&h=300&fit=crop",
      category: "Ocean",
      tags: ["ocean", "beach", "tropical"],
      altText: "Turquoise ocean waves on white sand beach",
      hoverText: "View Ocean Breeze",
      lightboxEnabled: true,
      order: 2,
      stats: { views: 2810, likes: 214 },
    },
    {
      title: "Forest Canopy",
      description: "Sunlight filtering through a dense emerald canopy of old-growth trees.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=400&h=300&fit=crop",
      category: "Forest",
      tags: ["forest", "trees", "nature"],
      altText: "Sunlight through forest canopy",
      hoverText: "View Forest Canopy",
      lightboxEnabled: true,
      order: 3,
      stats: { views: 1950, likes: 163 },
    },
    {
      title: "Mountain Lake",
      description: "Crystal-clear lake reflecting towering mountain peaks at dawn.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1439853949212-36589f9f2a47?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1439853949212-36589f9f2a47?w=400&h=300&fit=crop",
      category: "Mountains",
      tags: ["lake", "mountains", "reflection"],
      altText: "Mountain lake reflection at dawn",
      hoverText: "View Mountain Lake",
      lightboxEnabled: true,
      order: 4,
      stats: { views: 4100, likes: 342 },
    },
    {
      title: "Desert Dunes",
      description: "Sweeping golden sand dunes stretching endlessly under a blazing sun.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=400&h=300&fit=crop",
      category: "Desert",
      tags: ["desert", "dunes", "sand"],
      altText: "Golden sand dunes in the desert",
      hoverText: "View Desert Dunes",
      lightboxEnabled: true,
      order: 5,
      stats: { views: 2200, likes: 178 },
    },
    {
      title: "Autumn Trail",
      description: "A winding path through a forest ablaze with fall colors.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1475924156734-496f6cac6ec1?w=400&h=300&fit=crop",
      category: "Forest",
      tags: ["autumn", "trail", "foliage"],
      altText: "Winding autumn trail through colorful forest",
      hoverText: "View Autumn Trail",
      lightboxEnabled: true,
      order: 6,
      stats: { views: 2640, likes: 198 },
    },
    {
      title: "Waterfall Mist",
      description: "Powerful waterfall cascading into a misty emerald pool below.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1433086966358-54859d0ed716?w=400&h=300&fit=crop",
      category: "Water",
      tags: ["waterfall", "mist", "nature"],
      altText: "Waterfall cascading into misty pool",
      hoverText: "View Waterfall Mist",
      lightboxEnabled: true,
      order: 7,
      stats: { views: 3100, likes: 241 },
    },
    {
      title: "Snowy Pines",
      description: "Snow-laden pine trees standing silent in a winter wonderland.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1418985991508-e47386d96a71?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1418985991508-e47386d96a71?w=400&h=300&fit=crop",
      category: "Forest",
      tags: ["snow", "winter", "pines"],
      altText: "Snow-covered pine trees in winter",
      hoverText: "View Snowy Pines",
      lightboxEnabled: true,
      order: 8,
      stats: { views: 1870, likes: 152 },
    },
  ]);

  const natureGallery = await Gallery.create({
    title: "Nature's Canvas",
    subtitle: "Breathtaking landscapes from around the world",
    description: "A curated selection of nature photography capturing the raw beauty of our planet.",
    layoutType: "grid",
    allowFilter: true,
    categories: [
      { name: "All", slug: "all" },
      { name: "Mountains", slug: "mountains" },
      { name: "Ocean", slug: "ocean" },
      { name: "Forest", slug: "forest" },
      { name: "Desert", slug: "desert" },
      { name: "Water", slug: "water" },
    ],
    items: natureItems.map((i) => i._id),
    sectionOrder: 1,
    isActive: true,
  });

  console.log("Nature gallery seeded:", natureGallery.title);

  // ── COLLECTION 2: Urban & Architecture ──
  const urbanItems = await GalleryItem.insertMany([
    {
      title: "City Skyline",
      description: "Glowing metropolitan skyline reflected in harbor waters at twilight.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=400&h=300&fit=crop",
      category: "Architecture",
      tags: ["city", "skyline", "night"],
      altText: "City skyline at night reflected in water",
      hoverText: "View City Skyline",
      lightboxEnabled: true,
      order: 1,
      stats: { views: 6100, likes: 480 },
    },
    {
      title: "Gothic Cathedral",
      description: "Intricate Gothic architecture soaring toward the heavens.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=400&h=300&fit=crop",
      category: "Architecture",
      tags: ["gothic", "cathedral", "stone"],
      altText: "Gothic cathedral architecture",
      hoverText: "View Gothic Cathedral",
      lightboxEnabled: true,
      order: 2,
      stats: { views: 2890, likes: 221 },
    },
    {
      title: "Neon Streets",
      description: "Rain-soaked city streets reflecting neon signs at midnight.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1519501025264-65ba15a82390?w=400&h=300&fit=crop",
      category: "Street",
      tags: ["neon", "night", "rain"],
      altText: "Neon signs reflected in rainy streets",
      hoverText: "View Neon Streets",
      lightboxEnabled: true,
      order: 3,
      stats: { views: 4200, likes: 335 },
    },
    {
      title: "Modern Bridge",
      description: "Steel and glass bridge spanning a vast urban waterway.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1477414956199-7dafc86a4176?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1477414956199-7dafc86a4176?w=400&h=300&fit=crop",
      category: "Architecture",
      tags: ["bridge", "steel", "modern"],
      altText: "Modern steel bridge over urban waterway",
      hoverText: "View Modern Bridge",
      lightboxEnabled: true,
      order: 4,
      stats: { views: 3300, likes: 265 },
    },
    {
      title: "Subway Rush",
      description: "Motion blur of commuters rushing through a busy underground station.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?w=400&h=300&fit=crop",
      category: "Street",
      tags: ["subway", "motion", "commute"],
      altText: "Busy subway station with motion blur",
      hoverText: "View Subway Rush",
      lightboxEnabled: true,
      order: 5,
      stats: { views: 2100, likes: 167 },
    },
    {
      title: "Rooftop Garden",
      description: "Lush rooftop garden blooming above the concrete cityscape.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
      category: "Architecture",
      tags: ["rooftop", "garden", "urban"],
      altText: "Rooftop garden above city",
      hoverText: "View Rooftop Garden",
      lightboxEnabled: true,
      order: 6,
      stats: { views: 1980, likes: 154 },
    },
  ]);

  const urbanGallery = await Gallery.create({
    title: "Urban & Architecture",
    subtitle: "Cities, structures, and streets that define modern life",
    description: "A bento-style showcase of urban landscapes and architectural marvels.",
    layoutType: "bento",
    allowFilter: false,
    categories: [],
    items: urbanItems.map((i) => i._id),
    sectionOrder: 2,
    isActive: true,
  });

  console.log("Urban gallery seeded:", urbanGallery.title);

  // ── COLLECTION 3: People & Culture ──
  const peopleItems = await GalleryItem.insertMany([
    {
      title: "Festival Joy",
      description: "Vibrant colors and smiling faces at a traditional cultural festival.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&h=300&fit=crop",
      category: "Events",
      tags: ["festival", "culture", "celebration"],
      altText: "People celebrating at a colorful festival",
      hoverText: "View Festival Joy",
      lightboxEnabled: true,
      order: 1,
      stats: { views: 5400, likes: 432 },
    },
    {
      title: "Market Day",
      description: "Bustling local market overflowing with fresh produce and handcrafts.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1542838132-92c53300491e?w=400&h=300&fit=crop",
      category: "People",
      tags: ["market", "local", "culture"],
      altText: "Busy local market with fresh produce",
      hoverText: "View Market Day",
      lightboxEnabled: true,
      order: 2,
      stats: { views: 3200, likes: 256 },
    },
    {
      title: "Street Musician",
      description: "A lone musician filling the street with soulful melody.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop",
      category: "People",
      tags: ["music", "street", "artist"],
      altText: "Street musician performing outdoors",
      hoverText: "View Street Musician",
      lightboxEnabled: true,
      order: 3,
      stats: { views: 2700, likes: 215 },
    },
    {
      title: "Tech Conference",
      description: "Developers and innovators gathered at a global tech summit.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400&h=300&fit=crop",
      category: "Events",
      tags: ["tech", "conference", "networking"],
      altText: "Tech conference with developers",
      hoverText: "View Tech Conference",
      lightboxEnabled: true,
      order: 4,
      stats: { views: 4800, likes: 385 },
    },
    {
      title: "Yoga at Dawn",
      description: "Serene yoga practice silhouetted against a pastel sunrise.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=300&fit=crop",
      category: "Lifestyle",
      tags: ["yoga", "wellness", "sunrise"],
      altText: "Yoga silhouette at sunrise",
      hoverText: "View Yoga at Dawn",
      lightboxEnabled: true,
      order: 5,
      stats: { views: 3600, likes: 290 },
    },
    {
      title: "Hackathon Night",
      description: "Late-night coding session at a developer hackathon.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=400&h=300&fit=crop",
      category: "Events",
      tags: ["hackathon", "coding", "night"],
      altText: "Developers coding at hackathon",
      hoverText: "View Hackathon Night",
      lightboxEnabled: true,
      order: 6,
      stats: { views: 2900, likes: 234 },
    },
  ]);

  const peopleGallery = await Gallery.create({
    title: "People & Culture",
    subtitle: "Human stories from festivals, markets, and gatherings",
    description: "A celebration of human connection, creativity, and community.",
    layoutType: "grid",
    allowFilter: true,
    categories: [
      { name: "All", slug: "all" },
      { name: "Events", slug: "events" },
      { name: "People", slug: "people" },
      { name: "Lifestyle", slug: "lifestyle" },
    ],
    items: peopleItems.map((i) => i._id),
    sectionOrder: 3,
    isActive: true,
  });

  console.log("People gallery seeded:", peopleGallery.title);

  // ── COLLECTION 4: Abstract & Digital Art ──
  const abstractItems = await GalleryItem.insertMany([
    {
      title: "Liquid Dreams",
      description: "Flowing liquid paint creating mesmerizing color patterns.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1541701494587-cb58502866ab?w=400&h=300&fit=crop",
      category: "Abstract",
      tags: ["liquid", "paint", "colorful"],
      altText: "Liquid paint abstract art",
      hoverText: "View Liquid Dreams",
      lightboxEnabled: true,
      order: 1,
      stats: { views: 4100, likes: 328 },
    },
    {
      title: "Geometric Pulse",
      description: "Sharp geometric shapes pulsing with electric neon energy.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=400&h=300&fit=crop",
      category: "Digital",
      tags: ["geometric", "neon", "digital"],
      altText: "Geometric neon digital art",
      hoverText: "View Geometric Pulse",
      lightboxEnabled: true,
      order: 2,
      stats: { views: 3500, likes: 280 },
    },
    {
      title: "Smoke Trails",
      description: "Ethereal wisps of colored smoke dancing against a dark background.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1553356084-58ef4a67b2a7?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1553356084-58ef4a67b2a7?w=400&h=300&fit=crop",
      category: "Abstract",
      tags: ["smoke", "color", "ethereal"],
      altText: "Colorful smoke trails against dark background",
      hoverText: "View Smoke Trails",
      lightboxEnabled: true,
      order: 3,
      stats: { views: 2800, likes: 224 },
    },
    {
      title: "Crystal Formation",
      description: "Macro shot of crystalline structures refracting rainbow light.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400&h=300&fit=crop",
      category: "Macro",
      tags: ["crystal", "macro", "rainbow"],
      altText: "Crystal formation refracting rainbow light",
      hoverText: "View Crystal Formation",
      lightboxEnabled: true,
      order: 4,
      stats: { views: 3200, likes: 256 },
    },
    {
      title: "Neural Network",
      description: "Digital visualization of a neural network in glowing blue.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&h=300&fit=crop",
      category: "Digital",
      tags: ["ai", "neural", "tech"],
      altText: "Digital neural network visualization",
      hoverText: "View Neural Network",
      lightboxEnabled: true,
      order: 5,
      stats: { views: 5100, likes: 408 },
    },
    {
      title: "Fractal Universe",
      description: "Infinitely complex fractal patterns spiraling into the void.",
      mediaType: "image",
      mediaUrl: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=800&h=600&fit=crop",
      thumbnail: "https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=400&h=300&fit=crop",
      category: "Abstract",
      tags: ["fractal", "space", "infinite"],
      altText: "Fractal spiral patterns in space",
      hoverText: "View Fractal Universe",
      lightboxEnabled: true,
      order: 6,
      stats: { views: 4400, likes: 352 },
    },
  ]);

  const abstractGallery = await Gallery.create({
    title: "Abstract & Digital Art",
    subtitle: "Where imagination meets technology",
    description: "A bento showcase of digital art, abstract photography, and generative visuals.",
    layoutType: "bento",
    allowFilter: false,
    categories: [],
    items: abstractItems.map((i) => i._id),
    sectionOrder: 4,
    isActive: true,
  });

  console.log("Abstract gallery seeded:", abstractGallery.title);
  console.log("All galleries seeded successfully");
  process.exit(0);
};

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});